###
### 1. Open another terminal
### 2. Run the curl command

curl -X POST http://127.0.0.1:5000/certification/generateQuestions      
-H "Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW"     
-F "file=@/home/user/projects/certification_hub/data/certification_material.pdf"


